# Generated by Django 4.2.7 on 2023-11-17 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_owner_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('registration', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('mechanic_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('mileage', models.IntegerField()),
                ('service_type', models.CharField(choices=[('minor', 'Minor Repair'), ('major', 'Major Repair'), ('service', 'Service'), ('full', 'Full Service'), ('mot', 'MOT'), ('body', 'Body Work')], max_length=20)),
                ('description', models.TextField()),
                ('previous_owners_count', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.company')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.mechanic')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vehicle')),
            ],
        ),
    ]
