# Generated by Django 4.2.7 on 2023-11-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_owner_vehicle_current_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
    ]
