# Generated by Django 4.2.7 on 2023-11-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='fuel',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=20),
        ),
    ]
