# Generated by Django 4.2.7 on 2023-11-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_vehicle_fuel_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='cc',
            field=models.IntegerField(default=0),
        ),
    ]
